version: '3.8'

services:
  db:
    container_name: users_ms_db
    build:
      context: ./
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./docker/postgres/.env.dev
    networks:
      - users_ms_network
  web:
    container_name: users_ms
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api/:/app
    ports:
      - 8000:8000
    env_file:
      - ./docker/api/.env.dev
    depends_on:
      - db
    networks:
      - users_ms_network


volumes:
  postgres_data:
networks:
  users_ms_network: